### ISSUE TITLE
Có dùng được cho dòng BQ263T không bạn

### ISSUE THREAD

**Issue by sunning97** [tunglamvghy/AsusS530UN-hackintosh#1]
Có dùng được cho dòng BQ263T không bạn
Mình tính cài bản catalina hoặc mojave

**Comment by Frankensten** [comment]
Hello! Thanks for your work for asus s530un!
And there is a problem: I try to use oc and boot successfully, but the keyboard does not work (led is working well), I can't type my password so that I can't  log in. I try to update oc to 0.56 but it doesn't work, either. 
How can I solve this problem?

**Comment by tunglamvghy** [comment]
> Có dùng được cho dòng BQ263T không bạn
> Mình tính cài bản catalina hoặc mojave

Mình nghĩ như nhau cả thôi, chung 1 dòng mà, khác mỗi ổ cứng đi kèm máy😅

**Comment by sunning97** [comment]
cảm ơn bạn, mình cài được rồi, nhưng khi mình cắm tai nghe vào thì âm thanh như bị nhoè đi, ko nghe rõ, còn loa ngoài thì bình thường, bạn có bịn như thế không

**Comment by tunglamvghy** [comment]
> cảm ơn bạn, mình cài được rồi, nhưng khi mình cắm tai nghe vào thì âm thanh như bị nhoè đi, ko nghe rõ, còn loa ngoài thì bình thường, bạn có bịn như thế không

Máy mình không bị. Bạn có yheer cài thử CodecCommander kext nhé

**Comment by tunglamvghy** [comment]
> cảm ơn bạn, mình cài được rồi, nhưng khi mình cắm tai nghe vào thì âm thanh như bị nhoè đi, ko nghe rõ, còn loa ngoài thì bình thường, bạn có bịn như thế không

Bạn có thể reset máy bằng cách giữ nút nguồn trong vài giây là ok nhé. 
Giải pháp lâu dài:
Gỡ bản update card âm thanh trong Windows để dùng Microsoft Driver và đừng để nó update😂

**Comment by sunning97** [comment]
mình cài mỗi mac thôi bạn, trước mình có thử cài dual thêm window mà không được, (mình có 2 ổ cứng 1 SSD để cài mac,ổ còn lại để lưu data, trước mình thử cài mac trên ở ssd còn win trên ở hdd mà vào boot option không thấy option của win đâu :D, mình thử tạo bootoption cũng không được, nên quay lại cài mỗi mac)

**Comment by tunglamvghy** [comment]
> mình cài mỗi mac thôi bạn, trước mình có thử cài dual thêm window mà không được, (mình có 2 ổ cứng 1 SSD để cài mac,ổ còn lại là hdd để lưu data, trước mình thử cài mac trên ở ssd còn win trên ở hdd mà vào boot option không thấy option của win đâu :D, mình thử tạo bootoption cũng không được, nên quay lại cài mỗi mac)

Nếu bị vậy thì bạn search cho mình và cài thử CodecCommander vào /L/E và check lại nhé 
Còn về việc dualboot với win thì bạn tạo phân vùng EFI mới trên HDD nữa rồi cài Win lên HDD nhé (nhưng win sẽ bị lag lắm do chạy bằng HDD, tốt nhất nên chia SSD làm 2, 1 cài win, 1 cài Mac, máy mình cũng thế mà). Khi đó vào Boot Option của BIOS (ấn Esc lúc khởi động) để chọn giữa Mac và Windows

**Comment by sunning97** [comment]
cảm ơn bạn. bạn nói rõ chỗ tạo thêm phân vùng EFI được không, mình cài lại thử : mình cài mac trước, xong cài win sau trên cùng ổ SSD. win nó write vô thẳng phân vùng EFI của mac. (thêm 1 folder microsoft trong EFI), bên mac vẫn boot bình thường sau khi cài win. nhưng khi mình ở mac rồi tắt máy chuyển sang win thì win thì nó load repair gì đó với check disk, lâu lâu còn không boot vô được

**Comment by tunglamvghy** [comment]
> cảm ơn bạn. bạn nói rõ chỗ tạo thêm phân vùng EFI được không, mình cài lại thử : mình cài mac trước, xong cài win sau trên cùng ổ SSD. win nó write vô thẳng phân vùng EFI của mac. (thêm 1 folder microsoft trong EFI), bên mac vẫn boot bình thường sau khi cài win. nhưng khi mình ở mac rồi tắt máy chuyển sang win thì win thì nó load repair gì đó với check disk, lâu lâu còn không boot vô được

Đợt máy mình thì mình cài Win trước, Mac sau
