### ISSUE TITLE
Open Core treo không chạy trên Big Sur

### ISSUE THREAD

**Issue by ngocanhnckh** [tunglamvghy/AsusS530UN-hackintosh#10]
Panic

**Comment by XuanPhat0603** [comment]
> Panic

anh chỉ em cách fix được không ạ?

**Comment by tunglamvghy** [comment]
Bản của mình chỉ hỗ trợ update trực tiếp từ macOS 10.15 lên thui chư sao hỗ trợ cài mới nhé.
