### ISSUE TITLE
Big sur 

### ISSUE THREAD

**Issue by BigD1979666** [tunglamvghy/AsusS530UN-hackintosh#11]
Hi, I've got a laptop with similar specs to yours and while I got big sur beta 2 running fine , I can't get beta 3 . I see there is an update to MacOS 11. Or the big sur beta 3 under system>updates. Which did you choose? What did you do, update from beta 2 or clean install?

**Comment by tunglamvghy** [comment]
I update from beta 2 using System Software Update

**Comment by BigD1979666** [comment]
Managed to install from USB with OC but can't get dw1560 to work. Other than that it's quite smooth.

**Comment by tunglamvghy** [comment]
Try to compile Broadcom kexts with latest commit.
