### ISSUE TITLE
Cách chuyển từ clover sang opencore?

### ISSUE THREAD

**Issue by XuanPhat0603** [tunglamvghy/AsusS530UN-hackintosh#12]
Như trên tiêu đề, em làm thế nào để chuyển từ clover sang opencore ạ?
Em có đọc theo hướng đẫn của anh là chép folder boot và OC vào rồi restart lại máy thì máy báo lỗi ạ?

**Comment by tunglamvghy** [comment]
Thêm -v vào boot-arg và chụp lại màn hình lỗi cho mình nhé.

**Comment by XuanPhat0603** [comment]
nó chỉ hiện recovery và reset nvram thôi anh

**Comment by tunglamvghy** [comment]
Cách chuyển từ clover sang opencore chi tiết.
https://github.com/dortania/OpenCore-Install-Guide/tree/master/clover-conversion
