### ISSUE TITLE
Update từ 10.15.6 lên bigsur

### ISSUE THREAD

**Issue by XuanPhat0603** [tunglamvghy/AsusS530UN-hackintosh#13]
Anh cho em hỏi khi vào mục install thì bị treo táo vậy ạ? Em update trực tiếp ạ. Đang sài opencore 0.6.0 ạ. ![Uploading 88975208...]()

**Comment by XuanPhat0603** [comment]
![image](https://user-images.githubusercontent.com/50132895/88975302-26969280-d2e4-11ea-9510-29ec411a86de.jpeg)
em up ảnh lại ạ

**Comment by tunglamvghy** [comment]
Khi update sẽ có 1 đoạn nó sẽ đơ tầm 15 - 20 phút. Cứ đợi nó qua thì sẽ cài được nhé.
Khi update thì nên thêm -v vào boot-args trong mục NVRAM ở config.plist nhé.
