### ISSUE TITLE
Function keyboard

### ISSUE THREAD

**Issue by diepnt90** [tunglamvghy/AsusS530UN-hackintosh#14]
Bạn ơi mình hỏi xíu. 

Mình ko dùng laptop giống bạn. Mình xài thinkpad. Ở catalina các phím f1,f2 hay f3,4 mặc định của mình là tăng giảm âm lượng với tăng giảm độ sáng. 

Mình vừa lên bug sur với efi bê nguyên sang chỉ là update mấy kext như lilu lên beta để chạy big sure. Nhưng các phím kể bên trên ko chạy. Bạn biết lý do ko. 
Mình cảm ơn

**Comment by tunglamvghy** [comment]
> Bạn ơi mình hỏi xíu.
> 
> Mình ko dùng laptop giống bạn. Mình xài thinkpad. Ở catalina các phím f1,f2 hay f3,4 mặc định của mình là tăng giảm âm lượng với tăng giảm độ sáng.
> 
> Mình vừa lên bug sur với efi bê nguyên sang chỉ là update mấy kext như lilu lên beta để chạy big sure. Nhưng các phím kể bên trên ko chạy. Bạn biết lý do ko.
> Mình cảm ơn

Bạn ơi, 2 hãng khác nhau mà @.@.
Hãng máy mình là Asus sẽ dùng asusSMC kext để chạy phím Fn. Máy bạn là Lenovo thì đương nhiên là ko chạy được kext đó đồng nghĩa với việc phím Fn ko hoạt động thôi.
Muốn hoạt động được thì bạn phải patch lại dsdt nhé. Vì hãng máy khác nhau thì dsdt lệch nhiều lắm. Nên tìm bản efi cùng hãng Lenovo

**Comment by diepnt90** [comment]
Cảm ơn banj nhé
