### ISSUE TITLE
Chỉnh đèn bàn phím không dùng được

### ISSUE THREAD

**Issue by superzeldalink** [tunglamvghy/AsusS530UN-hackintosh#15]
Máy mình đang dùng là S530UA. Mình vừa update lên Big Sur beta 4 nhưng đèn bàn phím chỉ ở một mức, mình không chỉnh được.
Bạn có cách nào fix không ạ?
Cảm ơn bạn!

**Comment by tunglamvghy** [comment]
Thử bản efi mới nhất chưa b? Máy mình vẫn dùng bthg. 
Bạn check lại nvram nhé, có khả năng nvram của bạn bị lỗi

**Comment by superzeldalink** [comment]
Dạ mình có thử rồi, reset nvram luôn rồi ạ

**Comment by tunglamvghy** [comment]
Quay thử video mình xem nào? Với gửi mình cái config.plist của bạn nhé.

**Comment by superzeldalink** [comment]
Dạ đây ạ
[Video](https://www.youtube.com/watch?v=Kr7RJOutmrM)
[config.plist.zip](https://github.com/tunglamvghy/AsusS530UN-hackintosh/files/5067768/config.plist.zip)

**Comment by tunglamvghy** [comment]
> Dạ đây ạ
> [Video](https://www.youtube.com/watch?v=Kr7RJOutmrM)
> [config.plist.zip](https://github.com/tunglamvghy/AsusS530UN-hackintosh/files/5067768/config.plist.zip)

Tắt bắt driver thử xem, như file config của mình chỉ để mỗi 3 cái: HFSplus, OpenRuntime, OpenCanopy thôi xem có lên ko nhé

**Comment by superzeldalink** [comment]
Dạ được rồi ạ
Cảm ơn bác ạ!
