### ISSUE TITLE
VivoBook S530Fn - Can't Boot - Catalina 10.15.6

### ISSUE THREAD

**Issue by tvieira20** [tunglamvghy/AsusS530UN-hackintosh#16]
Hi.
I have an ASUS VivoBook S530Fn (I7-8565U, 8GB RAM, UHD 620 + NVIDIA MX150, BCM4352Z BT+Wi-Fi Combo Card, NVMe + SSD) with Win10 and macOS Catalina 10.15.6

I want to ditch CLOVER for good and since I know almost nothing about OpenCore I decided to Copy your EFI and give it a shot. Unfortunately it doesn't boot and it hangs at the same step:

Photo of Verbose:
![IMG_2584](https://user-images.githubusercontent.com/55699311/91668268-6929d580-eb03-11ea-9d5d-e0ce322518e4.jpg)

I noticed it says something about the TrackPad and with the ACPI (doesn't say which..)

Any sugestions?
Thanks

**Comment by tunglamvghy** [comment]
> Hi.
> I have an ASUS VivoBook S530Fn (I7-8565U, 8GB RAM, UHD 620 + NVIDIA MX150, BCM4352Z BT+Wi-Fi Combo Card, NVMe + SSD) with Win10 and macOS Catalina 10.15.6
> 
> I want to ditch CLOVER for good and since I know almost nothing about OpenCore I decided to Copy your EFI and give it a shot. Unfortunately it doesn't boot and it hangs at the same step:
> 
> Photo of Verbose:
> ![IMG_2584](https://user-images.githubusercontent.com/55699311/91668268-6929d580-eb03-11ea-9d5d-e0ce322518e4.jpg)
> 
> I noticed it says something about the TrackPad and with the ACPI (doesn't say which..)
> 
> Any sugestions?
> Thanks

Your processor is different from mine. So, just disable  ssdt-data that is related to my processor and try again.

**Comment by tunglamvghy** [comment]
Or you can try this: https://github.com/Jie2GG/Hackintosh-ASUS-S5300FN

**Comment by tvieira20** [comment]
> > Hi.
> > I have an ASUS VivoBook S530Fn (I7-8565U, 8GB RAM, UHD 620 + NVIDIA MX150, BCM4352Z BT+Wi-Fi Combo Card, NVMe + SSD) with Win10 and macOS Catalina 10.15.6
> > I want to ditch CLOVER for good and since I know almost nothing about OpenCore I decided to Copy your EFI and give it a shot. Unfortunately it doesn't boot and it hangs at the same step:
> > Photo of Verbose:
> > ![IMG_2584](https://user-images.githubusercontent.com/55699311/91668268-6929d580-eb03-11ea-9d5d-e0ce322518e4.jpg)
> > I noticed it says something about the TrackPad and with the ACPI (doesn't say which..)
> > Any sugestions?
> > Thanks
> 
> Your processor is different from mine. So, just disable ssdt-data that is related to my processor and try again.

I’ll try that. Thanks



> Or you can try this: https://github.com/Jie2GG/Hackintosh-ASUS-S5300FN

That works like my Clover EFI: Great. But I can’t boot Big Sur with it.
Thanks anyways mate

**Comment by tunglamvghy** [comment]
> > > Hi.
> > > I have an ASUS VivoBook S530Fn (I7-8565U, 8GB RAM, UHD 620 + NVIDIA MX150, BCM4352Z BT+Wi-Fi Combo Card, NVMe + SSD) with Win10 and macOS Catalina 10.15.6
> > > I want to ditch CLOVER for good and since I know almost nothing about OpenCore I decided to Copy your EFI and give it a shot. Unfortunately it doesn't boot and it hangs at the same step:
> > > Photo of Verbose:
> > > ![IMG_2584](https://user-images.githubusercontent.com/55699311/91668268-6929d580-eb03-11ea-9d5d-e0ce322518e4.jpg)
> > > I noticed it says something about the TrackPad and with the ACPI (doesn't say which..)
> > > Any sugestions?
> > > Thanks
> > 
> > 
> > Your processor is different from mine. So, just disable ssdt-data that is related to my processor and try again.
> 
> I’ll try that. Thanks
> 
> > Or you can try this: https://github.com/Jie2GG/Hackintosh-ASUS-S5300FN
> 
> That works like my Clover EFI: Great. But I can’t boot Big Sur with it.
> Thanks anyways mate

Read the BigSur guide from dortania.
