### ISSUE TITLE
Battery charge is not 100% full, EFI not working with Big Sur

### ISSUE THREAD

**Issue by PLHB1712289** [tunglamvghy/AsusS530UN-hackintosh#19]
- Em gặp một số lỗi liên quan đến việc pin không được sạc đầy. Pin chỉ sạc tối đa tới 83%.
- Em có thử update lên MacOS Big Sur beta thì bộ EFI mặc định của a hoạt động tốt, nhưng khi e thay thế kext wifi brcm thì nó không hoạt động được và bị treo táo mặc dù ở bản MacOS Catalina 10.15.7 nó hoạt động rất ổn định.
- Phần Tool, e hay sử dụng ProperTree để snapshot thư mục cho nó nạp kext cho lẹ thì phần tool của a có khá nhiều các tool lòi ra thêm mỗi lần snapshot, không biết là a có thể tinh chỉnh bớt những tool không cần thiết được không? Chứ mỗi lần snapshot em đều phải copy lại khá là loằng ngoằn.

Cám ơn a vì những đóng góp cho cộng đồng :)) E vô tình biết a từ Heliport.

**Comment by superzeldalink** [comment]
1. Sạc 83% là vì bạn đã mở chế độ kéo dài tuổi thọ pin. Bạn có thể tắt ở "System Preferences -> Battery -> Battery Health -> bỏ tick "Manage battery longevity" (Kext "AsusSMC" mới của bác Hiệp hỗ trợ tính năng này)
2. Bạn xóa kext "AirPortBrcm4360_Injector.kext" trong "AirportBrcmFixup.kext\Contents\PlugIns" hoặc disable kext đó trong config.plist cũng được.
3. Này mình cũng chưa biết. Bạn có thể xóa mấy Drivers và Tools không sử dụng trong folder OC để ProperTree không add vào.
P/s: Mình không phải chủ thớt. Có gì sai thì chủ thớt vào sửa giúp em. Heheee :3

**Comment by PLHB1712289** [comment]
- Cám ơn bạn vì đã hỗ trợ. Mình đã fix được lỗi không đầy pin.
- Về việc không khởi động được thì sáng nay mình có đọc 1 bài trên **VNO hackintosh** thì có 1 bác nói về việc **VoodooInput** của **VoodooPS2Controller.kext** xung đột khiến cho máy bị panic. Và mình đã vào kiểm tra file **config.plist** của chủ thớt thì đúng thật, anh ấy **không có thêm VoodooInput** của **VoodooPS2Controller** trong khi đó mình đã sử dụng **ProperTree** để snapshot thì nó đã tự thêm vào khiến cho máy bị panic.

**Comment by tunglamvghy** [comment]
Về mục 3, Tool thì mình cũng không dùng mấy. Có thể xóa được nhưng thường mình hay update OC bằng cách copy cả cái OC mới đè lên OC cũ nên nó mới nhiều như vậy. Bạn ko thích có thể xóa đi nhé.
+ Thư mục Driver chỉ cần để lại HFSplus, OpenRuntime và OpenCanopy. Còn lại xóa hết.
+ Thư mục Tool để lại OpenShell

**Comment by PLHB1712289** [comment]
Cám ơn a.
Em muốn hỏi thêm về cái phần pin. Em và bạn em có máy giống nhau, cùng cài hackintosh, cùng một bộ EFI của anh nhưng máy bạn em bị chai pin nhiều nên mới bị 83% và có mục điều khiển trong battery. Còn của em thì không có cái mục giống như bạn ở trên chỉ.

**Comment by tunglamvghy** [comment]
> Cám ơn a.
> Em muốn hỏi thêm về cái phần pin. Em và bạn em có máy giống nhau, cùng cài hackintosh, cùng một bộ EFI của anh nhưng máy bạn em bị chai pin nhiều nên mới bị 83% và có mục điều khiển trong battery. Còn của em thì lại không có cái mục giống như bạn ở trên chỉ, có phải là do máy em ít bị chai pin hơn không anh nhỉ?

Cái này thì chắc đợi bản sau của AsusSMC. Chứ thường thig máy nào cũng sẽ có phần đó mà. Kiểm tra lại xem. Nếu không thì reset NVRAM đi
