### ISSUE TITLE
keyboard doesn't work

### ISSUE THREAD

**Issue by Frankensten** [tunglamvghy/AsusS530UN-hackintosh#2]
Hello! Thanks for your work for asus s530un!
And there is a problem: I try to use oc and boot successfully, but the keyboard does not work (led is working well), I can't type my password so that I can't log in. I try to update oc to 0.56 but it doesn't work, either.
How can I solve this problem?

**Comment by sunning97** [comment]
Hello. How to use the OC folder. I copy the clover folder in this repo  to EFI folder on mac os drive and copy kext from this repo os/kext to clover/kext/other but can't boot

**Comment by Frankensten** [comment]
OC is another tool to boot macOS. You can't use the driver which is made for oc on clover.
And I can't use OC well either, so maybe you need to check this site to learn more about it: [https://github.com/acidanthera/OpenCorePkg](url)

**Comment by sunning97** [comment]
I followed the instructions of this video but can't boot: https://www.youtube.com/watch?v=6KGuINOyHh0&t=744s

**Comment by sunning97** [comment]
this show when I boot to USB, please help me https://i.imgur.com/lnvQUbW.jpg

**Comment by Frankensten** [comment]
I found that model information is missing in the config.plist. You should boot macOS by clover first and use Opencore Configurator (a tool ssimilar to Clover Configurator) to add model information in config.plist.

**Comment by tunglamvghy** [comment]
@Frankensten  you can use usb keyboard and install VoodooPS2Controller kext to /L/E.
Because I install this kext in /L/E so I disable this kext in config.plist

**Comment by tunglamvghy** [comment]
> I found that model information is missing in the config.plist. You should boot macOS by clover first and use Opencore Configurator (a tool ssimilar to Clover Configurator) to add model information in config.plist.

Dont use OpenCore Configurator. Read the guide from OpenCore and Just use any Text Editor or Plist Editor to edit config.plist

**Comment by tunglamvghy** [comment]
> Hello! Thanks for your work for asus s530un!
> And there is a problem: I try to use oc and boot successfully, but the keyboard does not work (led is working well), I can't type my password so that I can't log in. I try to update oc to 0.56 but it doesn't work, either.
> How can I solve this problem?
There are some changes from OC v0.5.5 to 0.5.6, I've put an update to make OC v0.5.6 work.

**Comment by vinayrsk** [comment]
Hello ,I have same laptop and same model number . by copying the oc and boot folder in my EFI will it boot or I have to create it  currently I am using olarila Catalina but my audio is not working 
I tried to fix it but failed I used alc, vooodoohda,( patchedAppleHDA not tried) my audio codecs is Alc256 .so I decided to go for open core .and found this site  .can I use this oc and boot  folder suggest me

**Comment by tunglamvghy** [comment]
> Hello ,I have same laptop and same model number . by copying the oc and boot folder in my EFI will it boot or I have to create it.currently I am using olarila Catalina but my audio is not working .
> I tried to fix it but failed .I used alc, vooodoohda,( patchedAppleHDA not tried) my audio codecs is Alc256 .so I decided to go for open core .and found this site .can I use this oc and boot folder suggest me

I think you can use my EFI, but you must replace your own Serial Number, MLB, ... that related to Mac profile.
