### ISSUE TITLE
Black Screen on FaceTime

### ISSUE THREAD

**Issue by AbhishekRMX1901** [tunglamvghy/AsusS530UN-hackintosh#21]
![Screenshot 2020-10-10 at 7.41.26 PM.png](https://user-images.githubusercontent.com/69757774/95657259-2232f500-0b31-11eb-8329-b7beaba972e5.png)

When I opened FaceTime a black screen appears. Is this buggy in catalina .It worked fine for me earlier in Mojave .If there's a solution please do help me out.

**Comment by tunglamvghy** [comment]
> ![Screenshot 2020-10-10 at 7.41.26 PM.png](https://user-images.githubusercontent.com/69757774/95657259-2232f500-0b31-11eb-8329-b7beaba972e5.png)
> 
> When I opened FaceTime a black screen appears. Is this buggy in catalina .It worked fine for me earlier in Mojave .If there's a solution please do help me out.

Lam Tung:
Check camera in System Infomation.

If you have different spec with mine, you will need to delete USB patch and repatch it using Hackintool.

**Comment by AbhishekRMX1901** [comment]
![IMG_20201011_171555_869.jpg](https://user-images.githubusercontent.com/69757774/95677803-aba3ff00-0be5-11eb-8238-f68aba431382.jpg)
Hi there, I found this in system
