### ISSUE TITLE
STUCK AT 'APPLEPS2CONTROLLER...'

### ISSUE THREAD

**Issue by yllee36** [tunglamvghy/AsusS530UN-hackintosh#24]
Hi, I'm using ur EFI v1.1.5 to boot, but i faced a problem...
It stuck at that "appleps2controller..."
My laptop is asus vivobook s530fn, which have an i5-8265u cpu...

![image](https://user-images.githubusercontent.com/73753944/99150021-b2360280-26cc-11eb-981e-ec8343b8bba4.png)

**Comment by yllee36** [comment]
Hi, I replaced that cpufriend kext which i found in Internet and fit my processor. I also reset NVRAM every time when i boot to OC and had tried ur EFI v1.2. But i face a problem now.. It stuck at 'BuildActDeviceEntry exit', can u help me?

![IMG_20201115_141725](https://user-images.githubusercontent.com/73753944/99178396-a63e5500-274d-11eb-8f9b-235fa6f6e0fe.jpg)

**Comment by tunglamvghy** [comment]
> Hi, I replaced that cpufriend kext which i found in Internet and suitable for my processor. I also reset NVRAM every time when i boot to OC and had tried ur EFI v1.2. But i face a problem now.. It stuck at 'BuildActDeviceEntry exit', can u help me?
> 
> ![IMG_20201115_141725](https://user-images.githubusercontent.com/73753944/99178396-a63e5500-274d-11eb-8f9b-235fa6f6e0fe.jpg)

You need SSDT-AWAK to fix this problem because of your WhiskeyLake processor. Run SSDTTime on Windows to generate the ssdt.

**Comment by yllee36** [comment]
> > Hi, I replaced that cpufriend kext which i found in Internet and suitable for my processor. I also reset NVRAM every time when i boot to OC and had tried ur EFI v1.2. But i face a problem now.. It stuck at 'BuildActDeviceEntry exit', can u help me?
> > ![IMG_20201115_141725](https://user-images.githubusercontent.com/73753944/99178396-a63e5500-274d-11eb-8f9b-235fa6f6e0fe.jpg)
> 
> You need SSDT-AWAK to fix this problem because of your WhiskeyLake processor. Run SSDTTime on Windows to generate the ssdt.
> For further detail, read Dortania guide.

Hi, i am done with it. But now i face a new problem... It stuck at here... Is there anything have problem?
![Uploading IMG_20201115_150433.jpg…]()

**Comment by tunglamvghy** [comment]
> > > Hi, I replaced that cpufriend kext which i found in Internet and suitable for my processor. I also reset NVRAM every time when i boot to OC and had tried ur EFI v1.2. But i face a problem now.. It stuck at 'BuildActDeviceEntry exit', can u help me?
> > > ![IMG_20201115_141725](https://user-images.githubusercontent.com/73753944/99178396-a63e5500-274d-11eb-8f9b-235fa6f6e0fe.jpg)
> > 
> > 
> > You need SSDT-AWAK to fix this problem because of your WhiskeyLake processor. Run SSDTTime on Windows to generate the ssdt.
> > For further detail, read Dortania guide.
> 
> Hi, i am done with it. But now i face a new problem... It stuck at here... Is there anything have problem?
> 
> And also before it stuck, size of mouse pointer from big to small will temporary appear.
> ![IMG_20201115_150433](https://user-images.githubusercontent.com/73753944/99179343-a6dbe900-2757-11eb-8109-09693ddccf14.jpg)

I have never seen this problem. The log doesnt say any errors.

**Comment by yllee36** [comment]
> > > > Hi, I replaced that cpufriend kext which i found in Internet and suitable for my processor. I also reset NVRAM every time when i boot to OC and had tried ur EFI v1.2. But i face a problem now.. It stuck at 'BuildActDeviceEntry exit', can u help me?
> > > > ![IMG_20201115_141725](https://user-images.githubusercontent.com/73753944/99178396-a63e5500-274d-11eb-8f9b-235fa6f6e0fe.jpg)
> > > 
> > > 
> > > You need SSDT-AWAK to fix this problem because of your WhiskeyLake processor. Run SSDTTime on Windows to generate the ssdt.
> > > For further detail, read Dortania guide.
> > 
> > 
> > Hi, i am done with it. But now i face a new problem... It stuck at here... Is there anything have problem?
> > And also before it stuck, size of mouse pointer from big to small will temporary appear.
> > ![IMG_20201115_150433](https://user-images.githubusercontent.com/73753944/99179343-a6dbe900-2757-11eb-8109-09693ddccf14.jpg)
> 
> I have never seen this problem. The log doesnt say any errors.

Hi, i am done with it. It looks nice.Thanks for ur help :)
