### ISSUE TITLE
Not working Tuboboost on CPU.

### ISSUE THREAD

**Issue by parkyongsunk** [tunglamvghy/AsusS530UN-hackintosh#27]
I am currently using ASUS S510UN, a laptop with similar specifications. All other functions work well, but there is a CPU problem. Despite the turboboost speed of 4.0 GHz, it stays at 2.0 GHz. Was there a similar issue in your laptop?

**Comment by tunglamvghy** [comment]
> I am currently using ASUS S510UN, a laptop with similar specifications. All other functions work well, but there is a CPU problem. Despite the turboboost speed of 4.0 GHz, it stays at 2.0 GHz. Was there a similar issue in your laptop?

I think there are many repos on github that support Asus S510. You can follow it. This repo is only for S530UN. 
However, if you only have problem with cpu and no other problems, you can use this (https://github.com/stevezhengshiqi/one-key-cpufriend) to generate new CPUFriend kext for your laptop.
