### ISSUE TITLE
Reset NVRAM

### ISSUE THREAD

**Issue by Ffontillas** [tunglamvghy/AsusS530UN-hackintosh#28]
Hi, I have the same unit with you. after I prepare the recovery USB, I copied the BOOT and OC folder into the EFI Folder in the USB.
when I boot I got an icon saying RESET NVRAM.
![reset nvram](https://user-images.githubusercontent.com/78025424/105843373-94611400-6012-11eb-9c2c-6338822e858a.jpg)

What is the solution?

**Comment by tunglamvghy** [comment]
> Hi, I have the same unit with you. after I prepare the recovery USB, I copied the BOOT and OC folder into the EFI Folder in the USB.
> when I boot I got an icon saying RESET NVRAM.
> ![reset nvram](https://user-images.githubusercontent.com/78025424/105843373-94611400-6012-11eb-9c2c-6338822e858a.jpg)
> 
> What is the solution?

Change ScanPolicy to 0
