### ISSUE TITLE
Enable HDMI output

### ISSUE THREAD

**Issue by mrgian** [tunglamvghy/AsusS530UN-hackintosh#29]
I'm currently using this configuration on a ZenBook UX331UN, it's working well but I can't still figure out how to enable HDMI output.

**Comment by tunglamvghy** [comment]
> I'm currently using this configuration on a ZenBook UX331UN, it's working well but I can't still figure out how to enable HDMI output.

Using the latest commit, you will be able to use HDMI.

**Comment by xnyuq** [comment]
Mình dùng S430UN thì gặp lỗi nếu lúc login screen nhập mật khẩu xong đang cắm sẵn HDMI ra màn hình ngoài thì màn lap bị black screen còn màn hình ngoài vẫn hiện bình thường (làm secondary display) 😢
