### ISSUE TITLE
Booting problem

### ISSUE THREAD

**Issue by vinayrsk** [tunglamvghy/AsusS530UN-hackintosh#3]
First of all thanks for your work .I have same laptop and same model number and I used ur clover folder for booting but it doesn't boot  I put the model number in smbios then also it doesn't boot .then I tried verbose mode to see the problem. And I think there is some problem with IGPU . but I don't know how to fix it .. Need help i using clover
![IMG_20200331_211037](https://user-images.githubusercontent.com/60579342/78048030-c247de80-7396-11ea-9bca-6ac893434216.jpg)
![IMG_20200331_211424](https://user-images.githubusercontent.com/60579342/78048066-d095fa80-7396-11ea-8510-e70893c41435.jpg)

**Comment by vinayrsk** [comment]
I am using clover

**Comment by vinayrsk** [comment]
How to contact you  give me your Facebook  or telegram  link 
Since I have same laptop same model I will also learn how you patch and fix every thing (I am also a student) 
I am facing audio issues I have installed olarila catalina and audio is not working .initially it was working but after re-installing it doesn't work I tried many times but failed

**Comment by tunglamvghy** [comment]
> First of all thanks for your work .I have same laptop and same model number and I used ur clover folder for booting but it doesn't boot I put the model number in smbios then also it doesn't boot .then I tried verbose mode to see the problem. And I think there is some problem with IGPU . but I don't know how to fix it .. Need help i using clover
> ![IMG_20200331_211037](https://user-images.githubusercontent.com/60579342/78048030-c247de80-7396-11ea-9bca-6ac893434216.jpg)
> ![IMG_20200331_211424](https://user-images.githubusercontent.com/60579342/78048066-d095fa80-7396-11ea-8510-e70893c41435.jpg)

That problem was caused after updating to 10.15.4
Now I have to study on school, so if I have free time I'll try to fix it.
You can try to boot in to safe mode by adding -x to bootarg then compile the latest version of Whatevergreen kext from github to fix it
