### ISSUE TITLE
can not restart and shutdown

### ISSUE THREAD

**Issue by mhat89** [tunglamvghy/AsusS530UN-hackintosh#30]
hey thanks for share your efi.
i'm useing asus vivobook s14 X430FN 
Intel Core i7-8565U
i use your efi and modify it for intel uhd 620 code and it works fine. but when it is about to shutdown or restart it gets stuck.
![photo6220004087001361718](https://user-images.githubusercontent.com/13340686/110877158-8853bc00-830b-11eb-8c8a-2e8d777e73fc.jpg)

**Comment by tunglamvghy** [comment]
> hey thanks for share your efi.
> i'm useing asus vivobook s14 X430FN
> Intel Core i7-8565U
> i use your efi and modify it for intel uhd 620 code and it works fine. but when it is about to shutdown or restart it gets stuck.
> ![photo6220004087001361718](https://user-images.githubusercontent.com/13340686/110877158-8853bc00-830b-11eb-8c8a-2e8d777e73fc.jpg)

try the latest commit. If the problem is not solved, I think you should patch some Shutdown method in DSDT.

**Comment by mhat89** [comment]
thank you for responding to my problem
I've fixed it by adding SSDT-RHUB.aml and SSDT-USB.aml

**Comment by sunejasourabh121** [comment]
hey @mhat89! So I'm a beginner. I have the same laptop, how did you get the wifi and Bluetooth to work (considering you have it stock). Also if it's not much trouble for you do you mind sharing your boot/ installation drive which you created at the time of installing?

**Comment by mhat89** [comment]
sorry i have replaced the wifi card with Broadcom from macbook air.
of course this is my laptop efi, hope it helps
https://drive.google.com/drive/folders/11uo5y0q98vUkINuItFjHgrafnMvJptBE?usp=sharing

**Comment by sunejasourabh121** [comment]
> sorry i have replaced the wifi card with Broadcom from macbook air. of course this is my laptop efi, hope it helps https://drive.google.com/drive/folders/11uo5y0q98vUkINuItFjHgrafnMvJptBE?usp=sharing

Heyy man! Thanks a ton for the efi. I'll prolly try to make it over the holidays. Do you mind sharing a link for the wifi adaptor as well. Or do you think I should buy one of those plug and play models idk if they would work.

**Comment by mhat89** [comment]
I think a broadcom wifi card with an NGFF slot will suit.
I don't have the link for the wifi card, but maybe on aliexpress e-commerce they sell a lot
