### ISSUE TITLE
Audio And Theme

### ISSUE THREAD

**Issue by kliterexx** [tunglamvghy/AsusS530UN-hackintosh#31]
Audio input and output not working after replacing the latest EFI. GUI (Theme) is not working during selection of boot entries on latest EFI.

**Comment by tunglamvghy** [comment]
> Audio input and output not working after replacing the latest EFI. GUI (Theme) is not working during selection of boot entries on latest EFI.

Follow OpenCore guide or Dortania guide to enable Audio in OpenCanopy. Due to its delay in boot, I turned it off.

**Comment by kliterexx** [comment]
The audio is not working on main system after installing latest EFI. And how I turn on theme please tell.

**Comment by tunglamvghy** [comment]
> system

Try to hard restart your pc by holding the power button until your pc restart.

**Comment by kliterexx** [comment]
I have tried everything. I thing the ALC patch is not included in the EFI. Please resolve my issue. Old EFI were fine.
![Screenshot 2021-03-30 at 11 13 00 AM](https://user-images.githubusercontent.com/81588318/112939732-9bf38500-9149-11eb-8b29-a09c93074356.png)

**Comment by tunglamvghy** [comment]
Change the layout id in DeviceProperties from 77 to 13

**Comment by kliterexx** [comment]
That is fixed now. But how to enable gui (theme) please tell. Thank you.

**Comment by tunglamvghy** [comment]
> That is fixed now. But how to enable gui (theme) please tell. Thank you.

Now, I'm busy so wait for the next update in this repo. But remember to change layout-id to 13 everytime my repo update.

**Comment by tunglamvghy** [comment]
> > That is fixed now. But how to enable gui (theme) please tell. Thank you.
> 
> Now, I'm busy so wait for the next update in this repo. But remember to change layout-id to 13 everytime my repo update. Or you can update OC to the latest version, theme will appear again.

**Comment by kliterexx** [comment]
Okk. Thank you.

**Comment by tunglamvghy** [comment]
I've updated my repo and Theme work again
