### ISSUE TITLE
Asus Vivobook S430UN HDMI+Sleep+Fn key

### ISSUE THREAD

**Issue by xnyuq** [tunglamvghy/AsusS530UN-hackintosh#32]
Mình đang dùng Asus S430UN có cùng cấu hình với máy bạn, sử dụng EFI v1.3.3 ở trang release (lastest commit 210404 thì mình không dùng được do không nhận touchpad, USB keyboard/mouse, bàn phím laptop thì gõ 1 phím nhận đến 4-5 ký tự).
Mình đang gặp phải vài lỗi như sau mong bạn có thể giúp hỗ trợ hướng fix nếu có thời gian:

- HDMI hoạt động ổn nhưng khi boot máy mà cắm sẵn HDMI thì sau khi nhập password thì màn hình lap sẽ tối thui (có đèn nền), màn hình ngoài thì vẫn hiển thị được làm second screen (lỗi này mình cũng có gặp khi trước đó tự build EFI), lúc này nếu gập laptop và mở lại thi thoảng sẽ gặp hiện tượng màn lap bị trắng xoá, khởi động lại (không dùng HDMI) thì đèn nền màn laptop khá chập chờn trong một khoảng thời gian.
- Sleep không hoạt động, sẽ bị tắt nguồn, khởi động lên thì hiện lỗi Sleep wake failure in EFI.
- Fn keys thì hoạt động hết trừ Enter để sleep và Esc để tắt màn hình.

**Comment by tunglamvghy** [comment]
1. Hiện tại lỗi HDMI mình ko check được vì mình ko dùng mấy.
2. Dùng hackintool vào mục power để tắt hibernate đi.
3. Bạn tải kext AsusSMC về rồi trong đó có mục install AsusSMCDaemon. Cài cái đó vào là xong nhé.

**Comment by xnyuq** [comment]
Okey mình cảm ơn bạn nhé.
