### ISSUE TITLE
Fn  keyboard feature

### ISSUE THREAD

**Issue by xjwan110** [tunglamvghy/AsusS530UN-hackintosh#33]
hello,I have a problem and I want to ask for your help.My laptop is Asus V5000F. cpu:i5-10210u
I apply your SSDT－ATK－KABY to my EFI，
most of the Fn keyboard is working.But Fn+F8 to decrease keyboard brightness doesn't work. Fn+ESC is too.
My keyboard composition is the same as yours. Could you help me？ I sincerely need your help to solve the problem of decreasing keyboard brightness.Thanks.
My laptop is running Mac bigsur.
   
[Screenshot_2021_0507_194402](https://user-images.githubusercontent.com/81334842/117445979-f3e09100-af2a-11eb-9da8-5684e2440d7d.png)``

**Comment by tunglamvghy** [comment]
You have to find in your dumped DSDT the method to decrease your keyboard. Then replace it in SSDT-ATK-KABY.

**Comment by xjwan110** [comment]
[DSDT.zip](https://github.com/tunglamvghy/AsusS530UN-hackintosh/files/6441401/DSDT.zip)
No, I can't. I spend much time making SSDT of ps2k keyboard mapping.

**Comment by xjwan110** [comment]
[see.zip](https://github.com/tunglamvghy/AsusS530UN-hackintosh/files/6441463/see.zip)
there are  config and ssd-atk-kaby.aml
