### ISSUE TITLE
Display flickering while charging

### ISSUE THREAD

**Issue by Breaknum** [tunglamvghy/AsusS530UN-hackintosh#34]
While charging display flicker  and in battery mode it doesn't flicker 
Video link is below 👇
 @[Viedo](https://drive.google.com/file/d/10fNtfNyNr4Jvc8g3aTuAE7gdn3BrHL6A/view?usp=drivesdk)

**Comment by superzeldalink** [comment]
I also got this issue.
My laptop is S530UA

**Comment by tunglamvghy** [comment]
I still don't know how to fix this error. =))
Just happen when you change from battery mode to charging mode. So pls plug before turning on ur pc or restart your pc when you see this problem.

**Comment by tunglamvghy** [comment]
I'm trying to fix the flickering issue while changing from battery mode to charging mode. Check the latest update.
