### ISSUE TITLE
[Question] Does it works with S530UF?

### ISSUE THREAD

**Issue by mhrastegary77** [tunglamvghy/AsusS530UN-hackintosh#35]
Hi i'm sooo new to the hackintosh world(actualy i'm still not even entered) and just wanna know does it works with S530UF i7? 
and also you didn't say anything about finger print in README.md.

**Comment by tunglamvghy** [comment]
> Hi i'm sooo new to the hackintosh world(actualy i'm still not even entered) and just wanna know does it works with S530UF i7?
> and also you didn't say anything about finger print in README.md.

Yes, you can try this efi, I dont make sure it will work 100%, but at least, it may help you to boot to macOS setup

**Comment by Frankensten** [comment]
Does S530UF and S530UN only differ in CPU？If yes, I can say it does work well, I changed mainboard with i7 last year because they didn't have the i5 ones that time. And this EFI works well on my laptop now.

**Comment by tunglamvghy** [comment]
> Does S530UF and S530UN only differ in CPU？If yes, I can say it does work well, I changed mainboard with i7 last year because they didn't have the i5 ones that time. And this EFI works well on my laptop now.

Remember to regenerate the SSDT-DATA.aml via CPUFriendFriend (search Google for it)

**Comment by Frankensten** [comment]
i7-8550U has the same TDP-down value as i5-8250U, in fact these two CPUs only have tiny difference, I think it's no need to regenerate the SSDT-DATA.aml, right? 
![3](https://user-images.githubusercontent.com/25704713/128709248-7899ae9d-1dce-4408-9720-4e7dd7d469f5.png)

**Comment by Frankensten** [comment]
> > Does S530UF and S530UN only differ in CPU？If yes, I can say it does work well, I changed mainboard with i7 last year because they didn't have the i5 ones that time. And this EFI works well on my laptop now.
> 
> Remember to regenerate the SSDT-DATA.aml via CPUFriendFriend (search Google for it)

i7-8550U has the same TDP-down value as i5-8250U, in fact these two CPUs only have tiny difference, I think it's no need to regenerate the SSDT-DATA.aml, right?
![3](https://user-images.githubusercontent.com/25704713/128709381-4aa9a522-7137-4e93-96ad-cf0edda54866.png)
