### ISSUE TITLE
AppleALC trouble 

### ISSUE THREAD

**Issue by irinaxariton** [tunglamvghy/AsusS530UN-hackintosh#36]
After rebooting from windows to hackintosh, there is no sound at all. do you have some ideas on this issue?

**Comment by irinaxariton** [comment]
![Снимок экрана 2021-07-13 в 22 48 06](https://user-images.githubusercontent.com/87390962/125522723-87cf5b06-b2f3-4f5d-bf9f-30d8acccc6d7.png)
sure i tried to add boot-arg alctsel=1

**Comment by Frankensten** [comment]
i think holding the power botton to reboot will help

**Comment by tunglamvghy** [comment]
My laptop has the same issue, you need to hold the power button to reboot, that will fix the issue like @Frankensten mentioned.
