### ISSUE TITLE
Sound not working 

### ISSUE THREAD

**Issue by hoangthaibmvl** [tunglamvghy/AsusS530UN-hackintosh#4]
Hi i am using your OC for my hackintosh but the speaker not working 
![Screen Shot 2020-04-04 at 14 26 44](https://user-images.githubusercontent.com/29101561/78421241-55776180-7680-11ea-9dd7-e27d21c3ab80.png)
But my 3.5 jack work but the sound not clearly 
Thank you

**Comment by hoangthaibmvl** [comment]
Just reinstall mac it work fine

**Comment by tunglamvghy** [comment]
> Just reinstall mac it work fine

No. That's not the solution. You just hard turn off your laptop by keep holding power button for few seconds.

**Comment by hoangthaibmvl** [comment]
Hi it may be some mistake during install MacOS Because I new to this. Anyway thanks for you work <3

**Comment by hoangthaibmvl** [comment]
@tunglamvghy I have a problem with jack 3.5 headphone it not clearly . Do you have the same problem with me ?

**Comment by tunglamvghy** [comment]
> @tunglamvghy I have a problem with jack 3.5 headphone it not clearly . Do you have the same problem with me ?

No, my jack working fine. But you can try to install CodecCommander kext to /L/E and check if it works or not.

**Comment by hoangthaibmvl** [comment]
Ok i installed CodecCommander it not work clearly until i change balance to this it work perfectly 

![image](https://user-images.githubusercontent.com/29101561/79045482-8c77e500-7c35-11ea-8ad8-39350f226456.png)
