### ISSUE TITLE
Computer Restarts After Sleep Mode

### ISSUE THREAD

**Issue by Junren0966** [tunglamvghy/AsusS530UN-hackintosh#40]
Excuse me, my computer is vivobook s14.version 11.2.3.Your file driver works perfectly, but it automatically restarts after the computer hibernates.Excuse me, how to solve it? Thank you.

**Comment by tunglamvghy** [comment]
try to use hackintool, in power tab, click fix button.

**Comment by lqlam** [comment]
> Excuse me, my computer is vivobook s14.version 11.2.3.Your file driver works perfectly, but it automatically restarts after the computer hibernates.Excuse me, how to solve it? Thank you.

Use USB Mapping to replace USBInjectAlll and remove "no use port". It will fix your issue.

**Comment by datdadev** [comment]
> try to use hackintool, in power tab, click fix button.

I have tried, but it still getting the error
