### ISSUE TITLE
apfs module start 2485

### ISSUE THREAD

**Issue by gityasss** [tunglamvghy/AsusS530UN-hackintosh#42]
Hello tunglamvghy
i have an Asus Vivobook S15 model S530FN i7 8565u with Nvidia card and want to test hackintosh on it 
so i tried your EFI folder to start macos installation , but i get always stuck at Apfs module start 2485 line 
do you have any idea how to solve this issue please 
thanks in advance

**Comment by tunglamvghy** [comment]
Sorry for answering late. Your chipset model (i7 8565u - Whiskey Lake) is different from mine (i5 8250u - Kaby Lake Refresh). Therefore, you need to follow the Dortania guide to modify your EFI.
