### ISSUE TITLE
Can we update to Ventura?

### ISSUE THREAD

**Issue by mhrastegari** [tunglamvghy/AsusS530UN-hackintosh#43]
I've just been notified about a new update! can I update my S530UF to macOS Ventura? is it safe?

**Comment by tunglamvghy** [comment]
> I've just been notified about a new update! can I update my S530UF to macOS Ventura? is it safe?

I updated my repo. You can use it to update to macOS 13.

**Comment by mhrastegari** [comment]
Um I updated macOS and it's fine 🥲 plus it's my first hackintosh so, how can I update the drivers and EFI?

**Comment by tunglamvghy** [comment]
> Um I updated macOS and it's fine 🥲 plus it's my first hackintosh so, how can I update the drivers and EFI?
Drivers are included in the EFI
