### ISSUE TITLE
Unable to connect external monitor

### ISSUE THREAD

**Issue by sparktyy** [tunglamvghy/AsusS530UN-hackintosh#45]
Hello, after installing Ventura successfully, the hdmi interface cannot connect to the external display! Have you encountered this problem?

**Comment by raihanorium** [comment]
I'm also experiencing this after buying a new monitor.

**Comment by tunglamvghy** [comment]
I remove the HDMI patches since Ventura. I have re-added them to the latest update. Check it and tell me whether it works or not.

**Comment by raihanorium** [comment]
Works perfect! Thanks a lot.
