### ISSUE TITLE
compatible with S510UN?

### ISSUE THREAD

**Issue by cool2apps** [tunglamvghy/AsusS530UN-hackintosh#49]
Can I use this EFI to Asus S510UN which has similar specs with S530UN? When I tried this EFI with S510UN, it hangs at

USBToolBox: XHC: waitForMatchingService failed or timed out

Any idea how to fix this?

**Comment by tunglamvghy** [comment]
Please patch usb again using usbtoolbox. if you dont know, google it

**Comment by LeeBinder** [comment]
https://github.com/USBToolBox/tool/releases
