### ISSUE TITLE
Can't use Fn button after update to latest version

### ISSUE THREAD

**Issue by hoangthaibmvl** [tunglamvghy/AsusS530UN-hackintosh#5]
Hi after update to latest version i can only use Fn + F1  - F3 ; I can't use Fn + F4 - F8. I try to copy new kext to LE and rebuild my cache but it isn't working. Thank you

**Comment by tunglamvghy** [comment]
> Hi after update to latest version i can only use Fn + F1 - F3 ; I can't use Fn + F4 - F8. I try to copy new kext to LE and rebuild my cache but it isn't working. Thank you

I've updated a new version. Download it in Releases Tab to fix this.
