### ISSUE TITLE
Need help on info regarding upgrading to ventura or sonoma

### ISSUE THREAD

**Issue by warmachinesocial** [tunglamvghy/AsusS530UN-hackintosh#50]
Hi I currently have everything running on moneterey and figured out most of the things, it works fine but was using older version of opencore. Later I tried using latest opencore and ventura however most things broke, I'm using asus ux303ub i7 skylake 6500U, brightness, hdmi, vga, functions keys, sound all not working, is this expected?

**Comment by Allbyh** [comment]
I managed to install Sonoma on Skylake 6500U for HD520 OpenCore version 0.9.6. What's Working: Headphone out, Intel HD Graphics 520, Battery Indicator, Sleep, Wake, Restart, Shutdown, Brightness Slider, and Brightness Fn key [F11, F12], Trackpad with both I2CHID and PS/2, HDMI, HDMI Audio, Ethernet, SD Card Reader. What doesn't work: WIFI, Bluetooth, Internal Speaker out, Internal Mic In, Headphone Mic in. If you are interested, here you can obtain the EFI here. https://drive.google.com/file/d/17pobfgVRmmxxzzm23mkhKbp-k8q77RQ6/view?usp=sharing

**Comment by tunglamvghy** [comment]
> Hi I currently have everything running on moneterey and figured out most of the things, it works fine but was using older version of opencore. Later I tried using latest opencore and ventura however most things broke, I'm using asus ux303ub i7 skylake 6500U, brightness, hdmi, vga, functions keys, sound all not working, is this expected?

Your pc had many different specifications compared to mine. Try other repo.
