### ISSUE TITLE
Không phải lỗi! Đã tìm ra cách fix bàn phím và trackpad

### ISSUE THREAD

**Issue by Phu1237** [tunglamvghy/AsusS530UN-hackintosh#6]
Trong phần Kernel > Add mình sắp xếp theo thứ tự sau.
- BundlePath: VoodooPS2Controller.kext
ExecutablePath: Contents/MacOS/VoodooPS2Controller
- BundlePath: VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Trackpad.kext
ExecutablePath: Contents/MacOS/VoodooPS2Trackpad
- BundlePath: VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Mouse.kext
ExecutablePath: Contents/MacOS/VoodooPS2Mouse
- BundlePath: VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Keyboard.kext
ExecutablePath: Contents/MacOS/VoodooPS2Keyboard
- BundlePath: VoodooTSCSync.kext
ExecutablePath: Contents/MacOS/VoodooTSCSync
- BundlePath: VoodooI2C.kext/Contents/PlugIns/VoodooI2CServices.kext
ExecutablePath: Contents/MacOS/VoodooI2CServices
- BundlePath: VoodooI2C.kext/Contents/PlugIns/VoodooGPIO.kext
ExecutablePath: Contents/MacOS/VoodooGPIO
- BundlePath: VoodooI2C.kext
ExecutablePath: Contents/MacOS/VoodooI2C
- BundlePath: VoodooI2CHID.kext
ExecutablePath: Contents/MacOS/VoodooI2CHID

Tiện thể bản EFI mới nhất (12-04-2020) mình dùng không được toàn lỗi (Mất fn, mất bluetooth,...). Mình đang sử dụng bản EFI 16-03-2020 đã update các opencore, kext lên mới nhất ngoại trừ (AppleALC, IntelBluetoothFirmware, VirtualSMC, VoodooI2C) mọi thứ đều hoạt động với trackpad mình đã fix được.
[EFI.zip](https://github.com/tunglamvghy/AsusS530UN-hackintosh/files/4560355/EFI.zip)

**Comment by Phu1237** [comment]
[Uploading EFI.zip…]()
Mình nén hqua bị lỗi. Đây là file EFI hoàn chỉnh.

**Comment by tunglamvghy** [comment]
Okie. Cảm ơn nhé  mình check lại và cập nhật sau nhé.

**Comment by Phu1237** [comment]
Mà cái này nó có vấn đề là không dùng trackpad được ở macOS installer với Recovery. Bác xem thử có fix được không nha ^^ Cám ơn bác vì mấy bản efi này ^^

**Comment by tunglamvghy** [comment]
Ok. Có thời gian sẽ check lại. Đợt này bắt đầu đi học nên thi hơi nhìu, chẳng cả động vào máy để sửa.
