### ISSUE TITLE
Vấn đề về bios

### ISSUE THREAD

**Issue by XuanPhat0603** [tunglamvghy/AsusS530UN-hackintosh#9]
hi ad. Ad đang sử dụng bios phiên bản nào ạ? Em sài bios 305 bị lỗi. Anh có thể cho em hướng giải quyết không ạ?

**Comment by tunglamvghy** [comment]
bios làm sao?? mình cũng đang chạy bản 305.

**Comment by XuanPhat0603** [comment]
> bios làm sao?? mình cũng đang chạy bản 305.

em vị treo táo khi vào màn hình language ạ!!!

**Comment by tunglamvghy** [comment]
Bios thì bạn tắt cái secure boot và fast boot đi thôi. Còn treo táo hay không thì trong phân nvram > bootarg bạn thêm -v keepsyms=1 vào để xem là lỗi gì nhé

**Comment by XuanPhat0603** [comment]
> Bios thì bạn tắt cái secure boot và fast boot đi thôi. Còn treo táo hay không thì trong phân nvram > bootarg bạn thêm -v keepsyms=1 vào để xem là lỗi gì nhé

cảm ơn ad ạ. Để em coi thử ạ
